version: 2
updates:
  - package-ecosystem: gomod
    directory: /source
    schedule:
      interval: weekly
    target-branch: dev
    groups:
      go-deps:
        patterns: ["*"]
        update-types: [minor, patch]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: dev
    groups:
      actions:
        patterns: ["*"]
        update-types: [minor, patch]
