#!/bin/bash

# shellcheck disable=2004  ## Inappropriate complaining of "$/${} is unnecessary on arithmetic variables."
# shellcheck disable=2034  ## Unused variables.
# shellcheck disable=2119  ## Disable confusing and inapplicable warning about function's $1 meaning script's $1.
# shellcheck disable=2155  ## Disable check to 'Declare and assign separately to avoid masking return values'.
# shellcheck disable=2120  ## OK with declaring variables that accept arguments, without calling with arguments (this is 'overloading').
# shellcheck disable=2001  ## Complaining about use of sed istead of bash search & replace.
# shellcheck disable=2002  ## Useless use of cat. This works well though and I don't want to break it for the sake of syntax purity.
# shellcheck disable=2317  ## Can't reach
# shellcheck disable=2143  ## Used grep -q instead of echo | grep
# shellcheck disable=2162
# shellcheck disable=2207
# shellcheck disable=2181

##	Purpose: See fAbout() below.
##	Notes:
##		- THIS SCRIPT IS MANAGED ON GITHUB.
##		- See bottom of file for examples of numbers in various bases, and the space-saving percentages.
##	History: At bottom of this file. (Note: History for this is maintained outside of [or in addition to] git project.)

##	Copyright © 2022-2026 Jim Collier (ID: 1cv◂‡Vᛦ)
##	Licensed under the GNU General Public License v2.0 or later. Full text at:
##		https://spdx.org/licenses/GPL-2.0-or-later.html
##	SPDX-License-Identifier: GPL-2.0-or-later


## Boilerplate constants (but don't actually make read-only because of errors during script-managed recursion).
declare -i    doDebug=0
declare -i    runAsSudo=0
declare -i    doQuietly=0; [[ "${X9CONVERTBASE1_QUIET}" == "1" ]] && doQuietly=1
declare       thisVersion="v1.0.2"
declare       thisBuild="1mywgex"
declare       thisCopyrightYear="2023-2026"
declare       thisAuthor="Jim Collier (ID: 1cv◂‡Vᛦ)"


## Version, copyright, about, syntax (minified but not obfuscated)
## Note: Echoing rather than HEREDOC is preferrable becaus - while slower - that's not
##       an issue in this context, and more importantly, HEREDOC is too hard to manage
##       indentation, esp. for the fSyntax() section.

fVersion(){ { ((doQuietly)) || ((wasShown_Version)); } && return; wasShown_Version=1;
	fEcho_Clean "$(basename "${0}") ${thisVersion} build ${thisBuild}" ;:;}

fCopyright(){ { ((doQuietly)) || ((wasShown_Copyright)); } && return; wasShown_Copyright=1;
	fEcho_Clean ""
	wasShown_Version=0; fVersion
	fEcho_Clean "Copyright © ${thisCopyrightYear} ${thisAuthor}."
	fEcho_Clean "Project: https://github.com/jim-collier/convert-base-v1b"
	fEcho_Clean "Licensed under the GNU General Public License v2.0 or later. Full text at:"
	fEcho_Clean "  https://spdx.org/licenses/GPL-2.0-or-later.html"
	fEcho_Clean "No warranty."
	fEcho_Clean "" ;:;}

fAbout(){ { ((doQuietly)) || ((wasShown_About)); } && return; wasShown_About=1;
	fEcho_Clean ""
	#           X"-------------------------------------------------------------------------------"X
	fEcho_Clean "Converts from four possible input bases (including 10), to 29 possible output"
	fEcho_Clean "bases. Strictly positional notation conversion, not for binary-to-text"
	fEcho_Clean "encoding/decoding. (Though you can use the same common 2^N encoding bases such"
	fEcho_Clean "as base32 or base64, as positional notation.)"
	fEcho_Clean "" ;:;}

fSyntax(){  { ((doQuietly)) || ((wasShown_Syntax)); } && return; wasShown_Syntax=1;
	fEcho_Clean ""
	#           X"-------------------------------------------------------------------------------"X
	fEcho_Clean "Syntax: ${meName}  [optional args]  <NUMBER>  <OBASE>"
	fEcho_Clean "  Required arguments (in any order):"
	fEcho_Clean "    <NUMBER> .........: The input value to convert"
	fEcho_Clean "    <OBASE> ..........: The base to convert to (default 10 if not specified)"
	fEcho_Clean "  Optional arguments:"
	fEcho_Clean "    --ibase <base> ...: The input base (default 10 if not specified)"
	fEcho_Clean "    --from  <base> ...: Alias for '--ibase'"
	fEcho_Clean "    --obase <base> ...: Optional explicit flag for output base."
	fEcho_Clean "    --to  <base> .....: Alias for '--obase'"
	fEcho_Clean "    --lcase ..........: Lower case (for bases with alpha and only one case)"
	fEcho_Clean "    --clipin .........: Use clipboard for input"
	fEcho_Clean "    --clipout ........: Use clipboard for output"
	fEcho_Clean "    --silent .........: No CLI output. Also sets --clipout."
	fEcho_Clean "    --help, --about, --version [or -h, -a, -v]"
	fEcho_Clean "  Valid values for output <base>"
	fEcho_Clean "    Note: ST=Standard, PS=Pseudostandard, PUB=Published, C=Custom":
	fEcho_Clean "        2      ST  aka Binary ................. 0,1"
	fEcho_Clean "        8      ST  aka Octal .................. 0-7"
	fEcho_Clean "       10      ST  aka Decimal [default] ...... 0-9"
	fEcho_Clean "       16      ST  aka Hexedecimal ............ 0-9, A-F"
	fEcho_Clean "       26      PS  One-case alphabetic ........ A-Z"
	fEcho_Clean "       32[r]   ST  RFC 4648 §6 ................ A-Z, 2-7" #.......................... https://en.wikipedia.org/wiki/Base32
	fEcho_Clean "       32h     ST  RFC 4648 §7, 'Base32Hex' ... 0-9, A-V" #.......................... https://datatracker.ietf.org/doc/html/rfc4648#section-7
	fEcho_Clean "       32c     PUB Crockford's Base32 ......... 0-9, A-Z no I, L, O, U" #............ https://en.wikipedia.org/wiki/Base32#Crockford's_Base32
	fEcho_Clean "       32ws    PUB Word-safe Base32 ........... 2-9, CFGHJMPQRVWX, cfghjmpqrvwx" #... https://en.wikipedia.org/wiki/Base32#Word-safe_alphabet
	fEcho_Clean "       36      PS  Just alphanum .............. 0-9, A-Z" #.......................... https://en.wikipedia.org/wiki/Base36
	fEcho_Clean "       38host  C   Valid *nix host and domain name characters"
	fEcho_Clean "       39user  C   Valid *nix username characters"
	fEcho_Clean "       45email C   Valid HTML5 <email> address characters"
	fEcho_Clean "       48jc1ws C   Base 32ws + unicode symbols"
	fEcho_Clean "       52      PS  Both-case alphabetic ....... A-Z, a-z"
	fEcho_Clean "       62      PS  All alphanum ............... 0-9, A-Z, a-z" #..................... https://en.wikipedia.org/wiki/Base62
	fEcho_Clean "       64[r]   ST  RFC 4648 §4 ................ A-Z, a-z, 0-9, +, /" #............... https://en.wikipedia.org/wiki/Base64
	fEcho_Clean "       64u     ST  RFC 4648 §5, URL-safe ...... A-Z, a-z, 0-9, -, _" #............... https://en.wikipedia.org/wiki/Base64#Variants_summary_table
	fEcho_Clean "       64h     PS  Hex like, URL-safe ......... 0-9, A-Z, a-z, -, _" #............... https://en.wikipedia.org/wiki/Base64#Variants_summary_table
	fEcho_Clean "       64jc1   C   Base 62, +2 unicode symbols  0-9, A-Z, a-z, ʞ, λ"
	fEcho_Clean "       64jc1ws C   Base 48jcw + more unicode symbols"
	fEcho_Clean "      128jc1ws C   Base 64jcw + more unicode symbols"
	fEcho_Clean "      128jc1   C   Base 64jc  + more unicode symbols"
	fEcho_Clean "      256jc1   C   Base 128jc + more unicode symbols"
	fEcho_Clean "      288jc1   C   Base 256jc + more unicode symbols"
	fEcho_Clean "    v1 backwards-compatiable 'incongruous' word-safe bases:"
	fEcho_Clean "       48v1compat, 64v1compat, 128v1compat"
	fEcho_Clean "  Valid values for --ibase:"
	fEcho_Clean "    2, 8, 10, 16, 36"  ## Note: You might think that base32/base64 might work. But they don't. Also, fuzz-testing revealed that `bc` can't do base-26.
#	fEcho_Clean "    2, 8, 10, 16, 26, 36"  ## Note: You might think that base32/base64 might work. But they don't.
#	fEcho_Clean "Notes:"
#	fEcho_Clean "  ▸ Base 32 and 64 are often used for streaming binary-to-text encoding/de-"
#	fEcho_Clean "    coding, but there's no reason you can't use them for positional notation."
#	fEcho_Clean "  ▸ All bases are human-readable/comparable. But not even RFC standard bases >36"
#	fEcho_Clean "    will machine-sort properly with common sort regimes, eg LC_COLLATE=C.UTF-8."
	#           X"-------------------------------------------------------------------------------"X
	fEcho_Clean "" ;:;}


fMain(){
	## Generic variables
	local -i wasShown_Version=0; wasShown_Copyright=0; wasShown_About=0; wasShown_Syntax=0

	## Pre-validation
	_fMustBeInPath basename
	_fMustBeInPath bc

	## Template constants (this gest run twice if $runAsSudo == 1)
	local    -r doDebug="${doDebug}"  ## Make immutible for rest of script.
	local    -r meName="${meName}"    ## Make immutible for rest of script.

	## Template variables (soon to be constants)
	local -a allArgs=()

	## Standardized bases
	local -ra base2=($(echo {0..1}))
	local -ra base8=($(echo {0..7}))
	local -ra base10=($(echo {0..9}))
	local -ra base16=($(echo {0..9} {A..F}))
	local -ra base32r=($(echo {A..Z} {2..7})) #.............................................. RFC 4648
	local -ra base32h=($(echo {0..9} {A..V})) #.............................................. RFC 4648 hex
	local -ra base64r=($(echo {A..Z} {a..z} {0..9} "+ /")) #................................. RFC 4648
	local -ra base64u=($(echo {A..Z} {a..z} {0..9} "- _")) #................................. RFC 4648 url-safe variant
	local -ra base32w=(2 3 4 5 6 7 8 9 C F G H J M P Q R V W X c f g h j m p q r v w x) #.... Wordsafe

	## De-facto standards
	local -ra base26=($(echo {A..Z}))
	local -ra base32c=(0 1 2 3 4 5 6 7 8 9 A B C D E F G H J K M N P Q R S T V W X Y Z) #.... Crockford; no I, L, O, U; one famous programmer's proposal that has become a more-or-less de-facto accepted standard variant.
	local -ra base36=($(echo {0..9} {A..Z})) #............................................... Base36
	local -ra base52=($(echo {A..Z} {a..z}))
	local -ra base62=($(echo {0..9} {A..Z} {a..z})) #........................................ Base62

	## Very slight custom modifications
	local -ra base64h=($(echo {0..9} {A..Z} {a..z} "- _")) #................................. Hex-style base 64
	local -ra base64jc1=($(echo {0..9} {A..Z} {a..z} "ʞ λ")) #................................ Like 64h but more programmer (and visually) friendly +2 chars at the end. 1% more bytes that 64r|u on average for UTF-8 encoding, if evenly-distributed.

	## Custom 'word-safe', URL-safe, filesystem-safe, and programmer-friendly variants that strive to be CLI-width-friendly (but may not always render properly in every terminal or program with every font).
	## Note: Redefining these constitutes a breaking change with v1. But backward-compatible aliases are included below.
	local -ra base48jc1ws=(2 3 4 5 6 7 8 9 C F G H J M P Q R V W X c f g h j m p q r v w x ʞ λ μ ᛎ ᛏ ᛘ ᛯ ᛝ ᛦ ᛨ ᚠ ᚧ ᚬ ᚼ 🜣 🜥)
	local -ra base64jc1ws=(2 3 4 5 6 7 8 9 C F G H J M P Q R V W X c f g h j m p q r v w x ʞ λ μ ᛎ ᛏ ᛘ ᛯ ᛝ ᛦ ᛨ ᚠ ᚧ ᚬ ᚼ 🜣 🜥 🜿 🝅 ▵ ▸ ▿ ◂ ҂ ‡ ± ⁑ ÷ ∞ ≈ ≠ Ω Ʊ)
	local -ra base128jc1ws=(2 3 4 5 6 7 8 9 C F G H J M P Q R V W X c f g h j m p q r v w x ʞ λ μ ᛎ ᛏ ᛘ ᛯ ᛝ ᛦ ᛨ ᚠ ᚧ ᚬ ᚼ 🜣 🜥 🜿 🝅 ▵ ▸ ▿ ◂ ҂ ‡ ± ⁑ ÷ ∞ ≈ ≠ Ω Ʊ Ξ ψ Ϡ δ ϟ Ћ Ж Я Ѣ ф ¢ £ ¥ § ¿ ɤ ʬ ⍤ ⍩ ⌲ ⍋ ⍒ ⍢ Â Ĉ Ê Ĝ Ĥ Î Ĵ Ô Ŝ Û Ŵ Ŷ Ẑ â ĉ ê ĝ ĥ î ĵ ô ŝ û ŵ ŷ ẑ Ã Ẽ Ĩ Ñ Õ Ũ Ỹ ã ẽ ĩ ñ õ ũ ỹ Ä)

	## "Incorrect" backwards-compatiable with v1: Custom 'word-safe', URL-safe, filesystem-safe, and programmer-friendly variants that strive to be CLI-width-friendly (but may not always render properly in every terminal or program with every font).
	local -ra base48v1compat=(0 1 2 3 4 5 6 7 8 9 c f g h j m p q r v w x ʞ λ μ ᛎ ᛏ ᛘ ᛯ ᛝ ᛦ ᛨ ᚠ ᚧ ᚬ ᚼ 🜣 🜥 🜿 🝅 ▵ ▸ ▿ ◂ ҂ ‡ ± ⁑)
	local -ra base64v1compat=(0 1 2 3 4 5 6 7 8 9 C F G H J M P Q R V W X c f g h j m p q r v w x ʞ λ μ ᛎ ᛏ ᛘ ᛯ ᛝ ᛦ ᛨ ᚠ ᚧ ᚬ ᚼ 🜣 🜥 🜿 🝅 ▵ ▸ ▿ ◂ ҂ ‡ ± ⁑ ÷ ∞ ≈ ≠)
	local -ra base128v1compat=(0 1 2 3 4 5 6 7 8 9 C F G H J M P Q R V W X c f g h j m p q r v w x ʞ λ μ ᛎ ᛏ ᛘ ᛯ ᛝ ᛦ ᛨ ᚠ ᚧ ᚬ ᚼ 🜣 🜥 🜿 🝅 ▵ ▸ ▿ ◂ ҂ ‡ ± ⁑ ÷ ∞ ≈ ≠ Ω Ʊ Ξ ψ Ϡ δ ϟ Ћ Ж Я Ѣ ф ¢ £ ¥ § ¿ ɤ ʬ ⍤ ⍩ ⌲ ⍋ ⍒ ⍢ Â Ĉ Ê Ĝ Ĥ Ĵ Ŝ Ŵ Ŷ â ĉ ê ĝ ĥ ĵ ŝ ŵ ŷ Ã Ẽ Ñ Ỹ ã ẽ ñ ỹ Ä Ë Ẅ Ẍ Ÿ ä ë ẅ ẍ ÿ Á Ć É)

	## Custom (not 'word-safe'), URL-safe, filesystem-safe, and programmer-friendly variants that strive to be CLI-width-friendly (but may not always render properly in every terminal or program with every font).
	local -ra base128jc1=(0 1 2 3 4 5 6 7 8 9 A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z ʞ λ μ ᛎ ᛏ ᛘ ᛯ ᛝ ᛦ ᛨ ᚠ ᚧ ᚬ ᚼ 🜣 🜥 🜿 🝅 ▵ ▸ ▿ ◂ ҂ ‡ ± ⁑ ÷ ∞ ≈ ≠ Ω Ʊ Ξ ψ Ϡ δ ϟ Ћ Ж Я Ѣ ф ¢ £ ¥ § ¿ ɤ ʬ ⍤ ⍩ ⌲ ⍋ ⍒ ⍢ Â Ĉ Ê Ĝ Ĥ Î Ĵ Ô Ŝ Û Ŵ)
	local -ra base256jc1=(0 1 2 3 4 5 6 7 8 9 A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z ʞ λ μ ᛎ ᛏ ᛘ ᛯ ᛝ ᛦ ᛨ ᚠ ᚧ ᚬ ᚼ 🜣 🜥 🜿 🝅 ▵ ▸ ▿ ◂ ҂ ‡ ± ⁑ ÷ ∞ ≈ ≠ Ω Ʊ Ξ ψ Ϡ δ ϟ Ћ Ж Я Ѣ ф ¢ £ ¥ § ¿ ɤ ʬ ⍤ ⍩ ⌲ ⍋ ⍒ ⍢ Â Ĉ Ê Ĝ Ĥ Î Ĵ Ô Ŝ Û Ŵ Ŷ Ẑ â ĉ ê ĝ ĥ î ĵ ô ŝ û ŵ ŷ ẑ Ã Ẽ Ĩ Ñ Õ Ũ Ỹ ã ẽ ĩ ñ õ ũ ỹ Ä Ë Ï Ö Ü Ẅ Ẍ Ÿ ä ë ï ö ü ẅ ẍ ÿ Á Ć É Ǵ Í Ń Ó Ŕ Ś Ú Ẃ Ý Ź á ć é ǵ í ń ó ŕ ś ú ẃ ý ź Ā Ē Ī Ō Ū Ȳ ā ē ī ō ū ȳ Ǎ Č Ď Ě Ǧ Ȟ Ǩ Ň Ǒ Ř Š Ǔ ǎ č ď ě ǧ ȟ ǩ ň ǒ ř š ǔ ǝ ɹ ʇ ʌ ₸ ᛬ 웃 유 ㅈ ㅊ ㅍ ㅎ ㅱ ㅸ ㅠ ソ ッ ゞ ぅ ぇ ォ)
	local -ra base288jc1=(0 1 2 3 4 5 6 7 8 9 A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z ʞ λ μ ᛎ ᛏ ᛘ ᛯ ᛝ ᛦ ᛨ ᚠ ᚧ ᚬ ᚼ 🜣 🜥 🜿 🝅 ▵ ▸ ▿ ◂ ҂ ‡ ± ⁑ ÷ ∞ ≈ ≠ Ω Ʊ Ξ ψ Ϡ δ ϟ Ћ Ж Я Ѣ ф ¢ £ ¥ § ¿ ɤ ʬ ⍤ ⍩ ⌲ ⍋ ⍒ ⍢ Â Ĉ Ê Ĝ Ĥ Î Ĵ Ô Ŝ Û Ŵ Ŷ Ẑ â ĉ ê ĝ ĥ î ĵ ô ŝ û ŵ ŷ ẑ Ã Ẽ Ĩ Ñ Õ Ũ Ỹ ã ẽ ĩ ñ õ ũ ỹ Ä Ë Ï Ö Ü Ẅ Ẍ Ÿ ä ë ï ö ü ẅ ẍ ÿ Á Ć É Ǵ Í Ń Ó Ŕ Ś Ú Ẃ Ý Ź á ć é ǵ í ń ó ŕ ś ú ẃ ý ź Ā Ē Ī Ō Ū Ȳ ā ē ī ō ū ȳ Ǎ Č Ď Ě Ǧ Ȟ Ǩ Ň Ǒ Ř Š Ǔ ǎ č ď ě ǧ ȟ ǩ ň ǒ ř š ǔ ǝ ɹ ʇ ʌ ₸ ᛬ 웃 유 ㅈ ㅊ ㅍ ㅎ ㅱ ㅸ ㅠ ソ ッ ゞ ぅ ぇ ォ ゲ サ じ す ス せ ち づ で ネ ビ べ ぺ ま モ ゟ ヲ ½ ⅓ ⅔ ¼ ¾ ⅕ ⅖ ⅗ ⅘ ⅙ ⅚ ⅛ ⅜ ⅝ ⅞)

	## Custom; Special: ^[a-z_]([a-z0-9_-]){0,31}$; linux hostname (including domain - not case-sensitive, usually lower-case, and this is just the legal chars): [0-9a-z\-\.]
	local -ra base38hostname=($(echo {0..9} {a..z} "- ."))
	local -ra base39username=($(echo {0..9} {a..z} "- _ ."))
	local -ra base45email=($(echo {0..9} {a..z} "- _ % + . : @ [ ]"))

	## Args
	local    arg_inputVal=""
	local    arg_inBase=""
	local    arg_outBase=""
	local    inputVal=""
	local    inBase=""
	local    outBase=""
	local -i doLowerCase=0
	local -i doUseClipIn=0
	local -i doUseClipOut=0
	local -i doSilent=0
	fInit "${1}" "${2}" "${3}" "${4}" "${5}" "${6}" "${7}" "${8}" "${9}" "${10}" "${11}" "${12}" "${13}" "${14}" "${15}" "${16}" "${17}" "${18}" "${19}" "${20}" "${21}" "${22}" "${23}" "${24}" "${25}" "${26}" "${27}" "${28}" "${29}" "${30}" "${31}" "${32}"

	## Defaults
	[[ -z "${inBase}" ]] && inBase="10"
	[[ "${inBase}" != "10" ]] && [[ -z "${outBase}" ]] && outBase="10"
	((doSilent)) && doUseClipOut=1  ## If you use --silent without --clipout, nothing happens.

	## Get $inputVal from clipboard if appropriate
	if ((doUseClipIn)); then
		[[ -z "$(which xclip 2>/dev/null || true)" ]] && fThrowError "Can't get value from clipboard because 'xclip' is not installed."  "${FUNCNAME[0]}"
		inputVal="$(xclip -o -selection clipboard)"
	fi

	## Validate everything
	fValidate

	## Lock variables down that we can
	readonly allArgs
	readonly arg_inputVal
	readonly arg_inBase
	readonly arg_outBase
	readonly inputVal
#	readonly inBase   ## Can't lock this yet
	readonly outBase
	readonly doLowerCase
	readonly doUseClipIn
	readonly doUseClipOut
	readonly doSilent

	##
	## Make it so
	##

	## Environment varibles
	export BC_LINE_LENGTH=0

	## Convert ${inputVal} to base10 if necessary
	local inputVal_base10=0
	case "${inBase}" in
	#	"2"|"8"|"16"|"26"|"36")  ## Base 26 doesn't actually work
		"2"|"8"|"16"|"36")
			## As we've already validated, bc can only go up to base 36.
			inputVal_base10="$(bc <<< "ibase=${inBase}; ${inputVal}")"
			inBase="10"
			;;
		"10")
			## Already base10
			inputVal_base10=${inputVal}
	esac
	readonly inBase

	## Set obase for bc (for OUTput base); just an integer.
	bcObase=$(echo "${outBase}" | grep -iPo "[0-9]+" | head -n 1)

	## Check if output should also be base 10, in which case we're done.
	if [[ $bcObase -eq 10 ]]; then
		## User wants output in base 10, so we're done.
		fShowOutput "${inputVal_base10}"
		return
	fi

	## Convert ${inputVal_base10} input to ${bcObase}, which may output an array of digits if number as large and obase>16.
	local bcOutputDigitArray=""
	bcOutputDigitArray="$(bc <<< "obase=${bcObase}; ${inputVal_base10}")"

	## Validate; error if output has spaces, AND base <= 16 (which shouldn't be possible)
	[[ -n "$(echo "${bcOutputDigitArray}" | grep -iP "\ " )" ]] && [[ $bcObase -le 16 ]] && fThrowError "Unexpected error. 'bc' seems to have output an array, but base of ${bcObase} is <=16. 'bc' output: '${bcOutputDigitArray}'."  "${FUNCNAME[0]}"

	## If base is less than 16, it won't need any more work
	if [[ $bcObase -le 16 ]]; then
		fShowOutput "${bcOutputDigitArray}"
		return
	fi

	##
	## Substitute 'bc' output numbers with base characters
	##

	## Populate base character array
	case "${outBase}" in
		"26")                          local -ra baseValArray=("${base26[@]}")          ;;
		"32"|"32r"*)                   local -ra baseValArray=("${base32r[@]}")         ;;
		"32h"*)                        local -ra baseValArray=("${base32h[@]}")         ;;
		"32c"*)                        local -ra baseValArray=("${base32c[@]}")         ;;
		"36")                          local -ra baseValArray=("${base36[@]}")          ;;
		"38ho"*|"38jc1")               local -ra baseValArray=("${base38hostname[@]}")  ;;
		"39us"*|"39jc1")               local -ra baseValArray=("${base39username[@]}")  ;;
		"45em"*|"45jc1")               local -ra baseValArray=("${base45email[@]}")     ;;
		"52")                          local -ra baseValArray=("${base52[@]}")          ;;
		"62")                          local -ra baseValArray=("${base62[@]}")          ;;
		"64"|"64r"*)                   local -ra baseValArray=("${base64r[@]}")         ;;
		"64u"*)                        local -ra baseValArray=("${base64u[@]}")         ;;
		"64h"*)                        local -ra baseValArray=("${base64h[@]}")         ;;
		## Word-safe
		"32w"*)                        local -ra baseValArray=("${base32w[@]}")         ;;
		"48jc1w"*|"48jcw"*|"48j1w"*)   local -ra baseValArray=("${base48jc1ws[@]}")       ;;
		"64jc1w"*|"64jcw"*|"64j1w"*)   local -ra baseValArray=("${base64jc1ws[@]}")       ;;
		"128jc1w"*|"128jcw"*|"128j1w") local -ra baseValArray=("${base128jc1ws[@]}")      ;;
		## Custom JC
		"64jc1"|"64jc"|"64j1"|"64j1u") local -ra baseValArray=("${base64jc1[@]}")        ;;
		"128jc1"|"128jc"|"128j1")      local -ra baseValArray=("${base128jc1[@]}")       ;;
		"256jc1"|"256jc"|"256j1")      local -ra baseValArray=("${base256jc1[@]}")       ;;
		"288jc1"|"288jc"|"288j1")      local -ra baseValArray=("${base288jc1[@]}")       ;;
		## Backwards-compat
		"48v1compat")                  local -ra baseValArray=("${base48v1compat[@]}")  ;;
		"64v1compat")                  local -ra baseValArray=("${base64v1compat[@]}")  ;;
		"128v1compat")                 local -ra baseValArray=("${base128v1compat[@]}") ;;
	esac

	local -i index
	for item in $(bc <<< "obase=${bcObase}; ${inputVal_base10}"); do
		index=$((10#$item))  ## Leading 0s get interpreted by bash as octal, so convert to base10 and strip off leading 0s
		retVal="${retVal}${baseValArray[${index}]}"
	done

	fShowOutput "${retVal}"
	return

}


fShowOutput(){
	local inputStr="$1"
	## Lower case if desired and valid
	((doLowerCase)) && inputStr="${inputStr,,}"
	local -r inputStr="${inputStr}"
	if ((! doSilent)); then
		echo "${inputStr}"
	fi
	if ((doUseClipOut)); then
		echo -n "${inputStr}" | xclip -selection clipboard
	fi
}


fInit(){

	## Constants
	local -r _allArgs="$*"

	## Positional variables set (to not rely on detecting empty strings, which may themselves be valid settings)
	local -i argIsSet_InputVal=0

	## Generic variables
	local -i wasShown_Version=0; wasShown_Copyright=0; wasShown_About=0; wasShown_Syntax=0

	## Determine if we need to show help
	case " ${_allArgs,,} " in
		*" -h "*|*" -help "*|*" --help "*)                fCopyright ; fAbout ; fSyntax ; exit 0 ;;
		*" -a "*|*" -about "*|*" --about "*)              fCopyright ; fAbout           ; exit 0 ;;
		*" -v "*|*" -ver "*|*" --ver "*|*" --version "*)  fVersion                      ; exit 0 ;;
	esac
	if [[ -z "$(_fStrTrim_byecho "${_allArgs}")" ]]; then fCopyright; fAbout; fSyntax; exit 1; fi

	## Populate args array in a way that it stops at last non-empty value [GENERIC]
	local -i highestNonEmpty=0
	for ((i=1; i<=32; i++))              ; do  [[ -n "${!i}" ]] && highestNonEmpty=$i ; done
	for ((i=1; i<=highestNonEmpty; i++)) ; do  allArgs+=("${!i}")                     ; done
	unset highestNonEmpty

	## Init for loop
	local    tmpStr=""
	local    currentArg=""
	local    lastSwitch=""
	local -i expectingSwitchParamForNextArg=0
	local -i wasLastArg=0
	local -i emptyArgCount=0

	## Process arguments
	for currentArg in "${allArgs[@]}"; do
		#fEcho "fInin(): currentArg='${currentArg}' (start of loop)"  #DEBUG

		## Test if an option switch or not
		if [[ ${currentArg} == -* && ${currentArg} != *" "* && ${currentArg} != - ]]; then
			#fEcho "fInin(): currentArg='${currentArg}' (option switch)"  #DEBUG
			## It's an option switch

			## Check if this was supposed to NOT be a switch (eg expecting a parameter after previous switch)
			((${expectingSwitchParamForNextArg})) && fThrowError "Expecting a non-switch argument for '${lastSwitch}', instead got '${currentArg}'."  "${FUNCNAME[0]}"

			## Validate switches, and act on unary switches
			tmpStr="${currentArg,,}"  ## Lower case
			while [[ $tmpStr == -* ]]; do tmpStr="${tmpStr#-}"; done  ## Strip dashes off
			lastSwitch="${tmpStr}"    ## Remember lastSwitch
			case "${tmpStr}" in

				## Unitary switches (that take no extra params); Comment this test out if this script accepts no such thing.
				"lc"*|"lower"*)                  doLowerCase=1  ;;
				"clip"*"in"|"ic"*)               doUseClipIn=1  ;;
				"clip"*"out"|"oc"*)              doUseClipOut=1 ;;
				"silent")                        doSilent=1     ;;

				## Everything else, expecting a non-switch for next argument
				"ibase"|"inbase"|"in-base"|"basein"|"base-in"|"from")	expectingSwitchParamForNextArg=1 ;;
				"obase"|"outbase"|"out-base"|"baseout"|"base-out"|"to")	expectingSwitchParamForNextArg=1 ;;

				"") : ;;  ## Special case of user passing bare "--". Usually means "end of arg processing", but ignore for now.

				## ¯\_(ツ)_/¯
				*)  fThrowError  "Argument invalid or not expected in this context: '${currentArg}'."  "${FUNCNAME[0]}" ;;

			esac

		else

			## It's not an option switch; could be an option switch param, or a positional arg
			if ((expectingSwitchParamForNextArg)); then
				## Expecting option switch param
				case "${lastSwitch,,}" in
					"ibase"|"inbase"|"in-base"|"basein"|"base-in"|"from")
						arg_inBase="${currentArg}"
					;;
					"obase"|"outbase"|"out-base"|"baseout"|"base-out"|"to")
						arg_outBase="${currentArg}"
						argIsSet_arg_outBase=1
					;;
					*)
						fThrowError "Unkown parameters. Switch: '--${lastSwitch}', current parameter: '${currentArg}'."  "${FUNCNAME[0]}"
					;;
				esac
				expectingSwitchParamForNextArg=0

			else
				## Well it must be a positional arg then.
				if ((! argIsSet_InputVal)) && (( ! doUseClipIn)); then
					inputVal="${currentArg}"
					argIsSet_InputVal=1
				elif ((! argIsSet_arg_outBase)); then
					arg_outBase="${currentArg}"
					argIsSet_arg_outBase=1
				elif [[ -n "${currentArg}" ]]; then
					fThrowError "Unexpected positional argument: '${currentArg}'."  "${FUNCNAME[0]}"
				else
					fThrowError "Unknown error. Current arg: '${currentArg}'."  "${FUNCNAME[0]}"
				fi
			fi

		fi
		(($wasLastArg)) && break
	done

	## Validate
	((expectingSwitchParamForNextArg)) && fThrowError "Never received a parameter for switch '--${lastSwitch}'."

	## Normalize base names
	inBase="${arg_inBase}"
	outBase="${arg_outBase}"
	fNormalizeBaseName_byRef inBase
	fNormalizeBaseName_byRef outBase

}


fValidate(){

	## Validate
	[[ -z "${inputVal}" ]] && fThrowError "An input value must be specified."  "${FUNCNAME[0]}"
	[[ -z "${outBase}" ]] && fThrowError "An output base must be specified."  "${FUNCNAME[0]}"
	[[ -z "$(echo "x ${outBase} x" | grep -iP "x (2|8|10|16|26|32(c|h|r|w)?.*|36|38(ho.*|jc1)|39(us.*|jc1)|45(em.*|jc1)|(48|64|128)(j1w|jcw.*|jc1w.*)|52|62|64(h|r|u)?.*|64j1u|(64|128|256|288)(j1|jc|jc1)|(48|64|128)v1compat) x" || true)" ]] && fThrowError "Sorry, --obase of '${arg_outBase}' is not supported."  "${FUNCNAME[0]}"


	## Validate; make sure input characters all exist in input base
	local validBaseChars=""
	case "${inBase}" in
		"2")   validBaseChars="${base2[*]}"   ;;
		"8")   validBaseChars="${base8[*]}"   ;;
		"10")  validBaseChars="${base10[*]}"  ;;
		"16")  validBaseChars="${base16[*]}"  ;;
	#	"26")  validBaseChars="${base26[*]}"  ;;  ## Fuzz-testing revealed that `bc` can't do base-26.
		"36")  validBaseChars="${base36[*]}"  ;;
		*)     fThrowError "Sorry, --ibase of '${arg_inBase}' is not currently supported."  "${FUNCNAME[0]}" ;;
	esac
	local -r validBaseChars="${validBaseChars//" "/""}"  ## Strip out spaces
	local -r replaceWithChar="#"  ## 'Յ' = Armenian U+0545 and should never be used as a base char because it looks like ascii '3', but tr has problems with it.
	local -r testStr="$(tr -s "${validBaseChars}" "${replaceWithChar}" <<< "${inputVal}")"
	if [[ "${testStr}" != "${replaceWithChar}" ]]; then
		fThrowError "The input value of '${inputVal}' has characters outside the base array of '${validBaseChars}'."  "${FUNCNAME[0]}"
	fi

	## Validate lower case if desired and valid
	## UDPATE: Don't error if invalid in context, as the cognitive load on the user is too high; just benevolently fix the flag and move on.
	## It would be more robust to just scan or grep the contents for case. But for now this works.
	if ((doLowerCase)); then
		case "${outBase}" in
		#	"32w"*|"48"*|"52"|"62"|"64"*|"128"*|"256"*|"288"*)        fThrowError "The switch '--lcase' is incompatible with mixed-case base of ${arg_outBase}."  "${FUNCNAME[0]}"  ;; ## The lower-case switch is NOT valid in this context.
			"16"|"26"|"32"|"32r"*|"32h"*|"32c"*|"36")                 :                                                                                                             ;; ## The lower-case switch IS valid in this context.
			*)                                                        doLowerCase=0                                                                                                 ;; ## There are no upper-case chars anyway, so just disable the switch and don't complain.
		esac
	fi

}


fNormalizeBaseName_byRef(){
	local varName="$1"
	local varVal="${!varName}"

	## Base names to numbers
	case "${varVal,,}" in
		"bin"*) varVal="2"  ;;
		"oct"*) varVal="8"  ;;
		"dec"*) varVal="10" ;;
		"hex"*) varVal="16" ;;
	esac

	## Strip "b" or "base" off
	if   [[ -n "$(echo "${varVal}"  | grep -iP "base[0-9]+.*")" ]]; then varVal="${varVal/"base"/""}"
	elif [[ -n "$(echo "${varVal}"  | grep -iP "b[0-9]+.*")"    ]]; then varVal="${varVal/"b"/""}"; fi

	## Return
	eval "${varName}='${varVal}'"

}


fPromptToContinue(){
	local answer=""
	fEcho_Clean ""
	read -r -p "Continue? (y/n): " answer
	if [[ "${answer,,}" != "y" ]]; then
		fEcho "User aborted."
		exit 0
	fi
	fEcho_ResetBlankCounter
}


fCleanup(){ :
#	((! doSkipIntroStuff)) && ((! doQuietly)) && fEcho_Clean
}




##
##	Generic library
##	Purpose:
##		- Provide "library" functions to new scripts. But in a way that can be easily shared as single-script solutions.
##			- The old method of sourcing a '0_library_vN', while cleaner in terms of maintaining a whole library of scripts,
##			  made publishing/sharing more difficult. It's the classic tradeoff. But now that this code is extremely stable,
##			  it makes sense to be more publish & single-script frienly, and live with the downsides of such redundancy.

function _fStrTrim_byecho(){
	##	Purpose: Strip off leading and trailing whitespace from a string.
	##	Input:
	##		1 [REQUIRED]: String to trim.
	##	Returns:
	##		Modified string via echo. Capture with: MyVariable="$(_MyFunction "MyArg1" ...etc...)"
	##	History:
	##		- 20190826 JC: Created by copying from 0_library_v2.
	##		- 20190920 JC: Improved function header comments.
	local inputStr="$*"
	if [[ -n "${inputStr}" ]]; then
		outputStr="$(echo -e "${inputStr}" | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//' 2>/dev/null || true)"
	fi
	echo -n "${outputStr}"
}

function _fMustBeInPath(){
	##	History:
	##		- 20190826 JC: Created by copying from 0_library_v2.
	local -r programToCheckForInPath="$1"
	if [[ -z "${programToCheckForInPath}" ]]; then
		fThrowError "_fMustBeInPath(): Not program specified."
	elif [[ -z "$(command -v "${programToCheckForInPath}" 2>/dev/null || true)" ]]; then
		fThrowError "Not found in path: ${programToCheckForInPath}"
	fi
}


##
##	Generic echo-related stuff. (Minified.)
##
declare -i _wasLastEchoBlank=0
declare -i _isEchoInRawInlineMode=0
fEcho_ResetBlankCounter()     { _wasLastEchoBlank=0;      }
fEcho_WasLastEchoBlank_Set()  { { [[ "${1}" == "1" ]]  &&  _wasLastEchoBlank=1; }  ||  _wasLastEchoBlank=0;  }
fEcho_WasLastEchoBlank_Get()  { { ((_wasLastEchoBlank > 0))  &&  return 0; }  ||  return 1; }
fEcho_IsInRawInlineMode_Set() { { [[ "${1}" == "1" ]]  &&  _isEchoInRawInlineMode=1; }  ||  _isEchoInRawInlineMode=1; }  ## Script it telling fEcho* that something is going to be echoing to the screen in non-linefeed mode without its knowledge. (E.g. "echo -n 'something: '".)
fEcho_IsInRawInlineMode_Get() { { ((_isEchoInRawInlineMode))  &&  return 0; }  ||  return 1; }
fEcho_Clean(){
	((_isEchoInRawInlineMode))  &&  { echo; _wasLastEchoBlank=0; _isEchoInRawInlineMode=0; }
	if [[ -n "${1:-}" ]]; then echo -e "$*"; _wasLastEchoBlank=0; elif [[ $_wasLastEchoBlank -eq 0 ]]; then echo; _wasLastEchoBlank=1; fi; }
fEcho()                   { if [[ -n "$*" ]]; then fEcho_Clean "[ $* ]"; else fEcho_Clean ""; fi; }
fEcho_Force()             { fEcho_ResetBlankCounter; fEcho "$*";       }
fEcho_Clean_Force()       { fEcho_ResetBlankCounter; fEcho_Clean "$*"; }


##
##	Generic error-handling  stuff. (Minified.)
##	History
##		- 20190826 JC: Created by copying from 0_library_v2.
##		- 20190919 JC: Slight tweaks to improve newline output.

declare -i _wasCleanupRun=0
fThrowError(){
	local errMsg="$1"
	local funcName="$2"
	[[ -z "${errMsg}" ]] && errMsg="An error occurred."
	if [[ -z "${errMsg}" ]]; then
		errMsg="${meName}: ${errMsg}"
	else
		errMsg="${meName}.$2(): ${errMsg}"
	fi
	fEcho_Clean
	echo "${errMsg}" 1>&2
	fEcho_Clean_Force
	exit 1 ; }
function _fTrap_Exit(){
	[[ "${_wasCleanupRun}" != "0" ]] && return
	_wasCleanupRun=1
	_fSingleExitPoint "${1}" "${2}" "${3}" "${4}" "${5}" "${6}" "${7}" "${8}" "${9}" "${10}" "${11}" "${12}" "${13}" "${14}" "${15}" "${16}" "${17}" "${18}" "${19}" "${20}" "${21}" "${22}" "${23}" "${24}" "${25}" "${26}" "${27}" "${28}" "${29}" "${30}" "${31}" "${32}" ; }
function _fTrap_Error(){
	[[ "${_wasCleanupRun}" != "0" ]] && return
	_wasCleanupRun=1
	fEcho_ResetBlankCounter
	_fSingleExitPoint "${1}" "${2}" "${3}" "${4}" "${5}" "${6}" "${7}" "${8}" "${9}" "${10}" "${11}" "${12}" "${13}" "${14}" "${15}" "${16}" "${17}" "${18}" "${19}" "${20}" "${21}" "${22}" "${23}" "${24}" "${25}" "${26}" "${27}" "${28}" "${29}" "${30}" "${31}" "${32}" ; }
function _fTrap_Error_Ignore(){ true; }
function _fSingleExitPoint(){
	local -r signal="$1";  shift || true
	local -r lineNum="$1"; shift || true
	local -r errNum="$1";  shift || true
	local -r errMsg="$*"
	if [[ "${signal}" == "INT" ]]; then
		fEcho_Force
		fEcho "User interrupted."
		fCleanup  ## User cleanup
		exit 1
	elif [[ "${errNum}" != "0" ]] && [[ "${errNum}" != "1" ]]; then  ## Clunky string compare is less likely to fail than integer
		fEcho_Clean
		fEcho_Clean "Signal .....: '${signal}'"
		fEcho_Clean "Err# .......: '${errNum}'"
		fEcho_Clean "Error ......: '${errMsg}'"
		fEcho_Clean "At line# ...: '${lineNum}'"
		fEcho_Clean
		fCleanup  ## User cleanup
	else
		fCleanup  ## User cleanup
	fi; }
fDefineTrap_Error_Fatal(){ true; trap '_fTrap_Error ERR     ${LINENO} $? $_' ERR ; set -e; }
fDefineTrap_Error_Ignore(){      trap '_fTrap_Error_Ignore' ERR                  ; set +e; }


##
## Execution entry point
##

## Bash settings
set -e
set -E

## Error handling
fDefineTrap_Error_Fatal
trap '_fTrap_Error SIGHUP  ${LINENO} $? $_' SIGHUP
trap '_fTrap_Error SIGINT  ${LINENO} $? $_' SIGINT    ## CTRL+C
trap '_fTrap_Error SIGTERM ${LINENO} $? $_' SIGTERM
trap '_fTrap_Exit  EXIT    ${LINENO} $? $_' EXIT
trap '_fTrap_Exit  INT     ${LINENO} $? $_' INT
trap '_fTrap_Exit  TERM    ${LINENO} $? $_' TERM

## Common constants
declare    meName="$(basename "${BASH_SOURCE[0]}")"

## Main entry point
fMain "${1}" "${2}" "${3}" "${4}" "${5}" "${6}" "${7}" "${8}" "${9}" "${10}" "${11}" "${12}" "${13}" "${14}" "${15}" "${16}" "${17}" "${18}" "${19}" "${20}" "${21}" "${22}" "${23}" "${24}" "${25}" "${26}" "${27}" "${28}" "${29}" "${30}" "${31}" "${32}"


##	EXAMPLES: A big random base 10 number '987654321000055555555550000123456789' in various bases:
##	                      Reduction
##	   Base         Chars  Inc Orig  Number


##	OLD EXAMPLES: A big random base 10 number '2023090613425900000000000000001' in various bases:
##	                      Reduction
##	   Base         Chars  Inc Orig  Value
##       2            120            101111100011011100011110000110110111101101111000011101111110000011011000101110110010001100111110011111111010110100010101
##       8             40            5743343606675570357603305662147637726425
##      10             36            987654321000055555555550000123456789
##      16             30            BE371E1B7B7877E0D8BB233E7FAD15
##      26             26            EELUTHVVEDOHUKYXZVZLZBWNXL
##      32[r]          24            XY3R4G33PB36BWF3EM7H7LIV
##      32h            24            NORHS6RRF1RU1M5R4CV7VB8L
##      32c            24            QRVHW6VVF1VY1P5V4CZ7ZB8N
##      32w            24            hjqVr8qqQ3qw3g7q6Jx9xHCf
##      36             24            1L0CRVVUFHZO5Z4EHIOCISK5
##      38hostname     23            hdf8q5vjdfxd3t-gwe75u9v
##      39username     23            9v6de929rpvilgdb1gm7o_b
##      45email        22            i:_mxqm7shopf.y02f:75e
##      48jc1ws        22            6ᚠPv4ᛨHG2ᛘᛯᛘHᚧ9phgμCq7
##      52             21            vNoFHYtcznezzzJbezdYl
##      62             21            1OvZg4xLjgW5p6V6TBcCT
##      64[r]          20            vjceG3t4d+DYuyM+f60V
##      64u            20            vjceG3t4d-DYuyM-f60V
##      64h            20            lZSU6tjuT-3OkoC-VwqL
##      64j1           20            lZSU6tjuTʞ3OkoCʞVwqL
##      64jc1ws        20            🜥ᛎrw8‡ᚼ±vΩ5j🜣▵JΩx÷▿f
##     128jc1ws        18            3ΩqЯδ‡ĤŴŷÛŝ🜣â▸ĨỹĜf
##     128jc1          18            1ʞRᛨᛘt≠δ⍤Ϡ¿kЖp⍒Û≈L
##     256jc1          15            ítURĴĜÊčȞćZʞŴÁL
##     288jc1          15            aẌňẌỹńÓまĩćaÎɤŸỸ




##	History:
##		- 20230830 JC: Created from x9bsnaps as template.
##		- 20230901-0920 JC: Added bases and polished 'j1' character sets.
##		- 20230924 JC: Bug fix, inability to --lcase base 26.
##		- 20260411 JC: Removed base94ascii. There is some bug that puts filenames on the filesystem into the output. But it's not an important base to include.
##		- 20260417 JC:
##			- Removed a large amount of unused boilerplate, debugging, and profiling code that has been in here from day one.
##			- Allow switches to only have a single leading-dash, without complaining about invalid args.
##			- Remove some unnecessary code paths, such as arg-parser building a flat string of args.
##		- 20260423 JC: Breaking changes with v1 necessitated v1b. (v2 is already underway and even more different.)
##			- Redefined custom "word-safe" bases to be consistent with the published "32w" from Google, rather than halfway-consistent.
##			- Can no longer refer to bases by number alone, that aren't well-defined standards (e.g. 128).
##		- 20260424 JC: Removed base-26. Fuzz-testing revealed that `bc` can't do base-26.
##		- 20260425 JC: v1.0.0.
##		- 20260426 JC:
##			- v1.0.1, fully backwards compatible with v1.0.0.
##			- Fixed '--help' bug.
##			- Added '--from' as an alias for '--ibase'.
##			- Added optional ability to explicitly specify output base as a flag (--obase or --to), rather than as a positional argument.
##			- Updated --help text.
